---
# Creates App user and group in the system
- name: Create App user
  user: name={{ app_owner }} createhome=no home={{ app_home }} shell=/sbin/nologin state=present

# Checks whether App home directory already exists
- name: Check if App is already installed
  stat: path={{ app_home }}
  register: app_installed

# Download App package
- name: Download App
  get_url: url={{ app_url }} dest=/opt/{{ app_name }}-{{ app_version }}
  when: not app_installed.stat.exists

# Changes ownership of the app
- name: Change permissions of service
  file: path=/opt/{{ app_name }}-{{ app_version }} owner={{ app_owner }} group={{ app_group }} mode=555

# Changes ownership of the app
#- name: Change permissions of service
#  file: path=/opt/{{ app_name }}-{{ app_version }} owner={{ app_owner }} group={{ app_group }} mode=500

# Starts App
#- name: Start App
#  service: name={{ app_name }} state=started enabled=yes
